.\" Manpage for wid.
.\" Contact contact.scottforsberg@gmail.com.
.TH man 8 "07 Jun 2019" ".2" "wid man page"
.SH NAME
wid \- download images from a webpage 
.SH SYNOPSIS
wid [ -d PATH ] [ -u URL ]  [ -h ] [ -v ]
.SH DESCRIPTION
This program will download images found on a webpage url.
.SH OPTIONS
-d	save directory, default is current path

-u	url to download from

-v 	enables verbose output

-h 	display options
.SH SEE ALSO
wid --help
.SH BUGS
No known bugs.
.SH AUTHOR
Scott Forsberg (contact.scottforsberg@gmail.com)
